# -*- coding: utf-8 -*-
"""AppActividad2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FnAOBTqcVfwft_XSdF0lddLgqqeXvD77
"""

pip install streamlit

# Import
import streamlit as st
# Título de la página
st.title('Hola mundo. Esto es un titular')